### PR TITLE
python_isolate_header

### LINKED ISSUE #24: python_isolate header
**Description:**
Convert the TBE header into a Python-native data structure, making it easy to access and manipulate metadata.

**Developer Notes:**
- Store the extracted metadata as a dictionary or similar Python-native data structure, with keys representing the metadata fields( e.g., Title, Source) and ensure the metadata retain it's hierarchical structure.
- Implement logging (e.g., info or warning) to document and trace missing metadata fields without interrupting.

**Acceptance Criteria:**
- [x] metadata is stored in a dictionary using field names as keys
- [x] TBL sections and ATT attributes should be nested to reflect the TBE header hierarchy
- [x] metadata dictionary structure mirrors the original TBE header structure
- [x] separation of attributes within each TBL section
- [x] prompt errors for missing fields
- [x] handle unexpected formats, empty sections, and duplicate attributes without causing errors or data loss

### PR DESCRIPTION
**Pull request by Brijitha1609**
Fixes #24 

What was changed?
I implemented functionality to parse the TBE header and extract its metadata into a Python-native dictionary structure. The metadata now reflects the hierarchical structure of the TBE file, and it is easily accessible for further processing.

Why was it changed?
This change was made to ensure the TBE header data is organized into a structured format, allowing for easy manipulation and retrieval. By using a dictionary, the metadata can be accessed efficiently, and the structure mirrors the original TBE header. The update also improves error handling for missing metadata fields, unexpected formats, empty sections, and duplicate attributes.

How was it changed?
I added the parsing logic to extract metadata and store it in a dictionary format. Nested structures reflect TBL sections and ATT attributes. Logging was integrated to track missing fields, and error handling was improved to address edge cases. Additionally, the solution gracefully handles unexpected formats and reports warnings without interrupting the flow.

### CODE REVIEW

**Comment by suprajamannava17** [comment]
The output is not as expected and the issue states to isolate the header, but the resultant output is not depicting, so check this PR https://github.com/oss-slu/tbe/pull/101 ensuring you're meeting all the required criteria.

**Comment by Brijitha1609** [comment]
Thank you for the feedback! I've made the necessary changes to ensure the header is properly isolated, and the output now meets the expected format. Please let me know if anything else needs adjustment.

**Comment by suprajamannava17** [comment]
Great work implementing the isolate header functionality, @DeviPriya-Kolla you can approve the PR.

**Review by DeviPriya-Kolla — APPROVED** [review]
lgtm:

**Pull request merged**
